import {
  ConnectButton,
  getDefaultWallets,
  RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
// import {
//   ConnectKitProvider,
//   ConnectKitButton,
//   getDefaultClient,
// } from "connectkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { chain, configureChains, createClient, WagmiConfig } from "wagmi";
import { SocketBridge } from "../components/SocketBridge";
import styles from "../styles/Home.module.css";
import { publicProvider } from "wagmi/providers/public";

const Home: NextPage = () => {
  // const client = createClient(
  //   getDefaultClient({
  //     appName: "Some app",
  //   })
  // );
  const { chains, provider } = configureChains(
    [chain.polygon, chain.optimism, chain.arbitrum, chain.mainnet],
    [publicProvider()]
  );
  const { connectors } = getDefaultWallets({
    appName: "My RainbowKit App",
    chains,
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });

  // const [showBridge, setShowBridge] = useState<boolean>(false);
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>

            <p className={styles.description}>
              Get started by editing{" "}
              <code className={styles.code}>pages/index.tsx</code>
            </p>
            {/* <button onClick={() => setShowBridge(!showBridge)}>
              Show/Hide
            </button> */}

            {typeof window !== undefined && <SocketBridge />}
          </main>

          <iframe src="https://feat-individual-wallet-imports.dekg93h9tnxu3.amplifyapp.com/" height="1200" width="600" />
        </div>
      <ConnectButton />
      </RainbowKitProvider>
    </WagmiConfig>
  );
};

export default Home;
